# Generated by Django 5.0.7 on 2024-11-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0009_cartitem_color_cartitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
    ]
