# Generated by Django 5.0.7 on 2024-12-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0011_cartitem_color_cartitem_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='clothing',
            options={'verbose_name': 'Clothing Item', 'verbose_name_plural': 'Clothing Items'},
        ),
        migrations.AlterModelOptions(
            name='coffeemug',
            options={'verbose_name': 'Coffee Mug', 'verbose_name_plural': 'Coffee Mugs'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery Item', 'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Music', 'verbose_name_plural': 'Music'},
        ),
        migrations.AlterModelOptions(
            name='musicset',
            options={'verbose_name': 'Music Set', 'verbose_name_plural': 'Music Sets'},
        ),
        migrations.AlterModelOptions(
            name='post_index',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': 'Poster', 'verbose_name_plural': 'Posters'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
