# Generated by Django 5.0.7 on 2024-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0013_alter_cartitem_options_alter_cartitem_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
