# Generated by Django 5.0.7 on 2024-12-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0015_alter_cartitem_options_remove_cart_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White')], max_length=20)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='tonyapp.cartitem')),
            ],
        ),
    ]
