# Generated by Django 5.0.7 on 2024-12-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0016_cartitemunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItemUnit',
        ),
    ]
