# Generated by Django 5.0.7 on 2024-12-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0021_alter_clothing_color_alter_clothing_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/'),
        ),
    ]
