# Generated by Django 5.0.7 on 2024-12-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0022_clothing_image2_clothing_image3_clothing_image4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
