# Generated by Django 5.0.7 on 2024-12-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0023_alter_clothing_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicSet',
            new_name='Set',
        ),
    ]
