# Generated by Django 5.0.7 on 2024-12-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0025_rename_coffeemug_coffee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='coffee_mug',
        ),
        migrations.RenameModel(
            old_name='Set',
            new_name='music_set',
        ),
    ]
