# Generated by Django 5.0.7 on 2024-12-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0026_rename_coffee_coffee_mug_rename_set_music_set'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coffee_mug',
            new_name='CoffeeMug',
        ),
        migrations.RenameModel(
            old_name='music_set',
            new_name='MusicSet',
        ),
    ]
