# Generated by Django 5.0.7 on 2024-12-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0027_rename_coffee_mug_coffeemug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='poster',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='poster',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='poster',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='poster',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='poster',
            name='measures',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coffeemug',
            name='image',
            field=models.ImageField(upload_to='coffeemugs/'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
