# Generated by Django 5.0.7 on 2024-12-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0028_poster_image2_poster_image3_poster_image4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='image6',
        ),
    ]
