# Generated by Django 5.0.7 on 2024-12-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0029_remove_poster_image2_remove_poster_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicset',
            name='preview_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
