# Generated by Django 5.0.7 on 2024-12-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0031_remove_musicset_extra_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicset',
            name='duration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
