# Generated by Django 5.0.7 on 2024-12-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0032_musicset_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicset',
            name='duration',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='musicset',
            name='songs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicset',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
