# Generated by Django 5.0.7 on 2024-12-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0034_userinfo_alter_cartitem_options_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user_info',
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
