# Generated by Django 5.0.7 on 2024-12-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonyapp', '0037_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='sizes',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clothing',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clothing',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
